import './globals.css'
import { Providers } from '@/redux/provider'

import { ConfirmDialog } from 'primereact/confirmdialog';
import { Toast } from 'primereact/toast';

export const metadata = {
  title: 'Next Starter Kit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className='theme-light'>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}





const USER_DOMAIN = process.env.NEXT_PUBLIC_USER_URL
const ADMIN_DOMAIN = process.env.NEXT_PUBLIC_ADMIN_URL
const ADMIN_KEY = process.env.NEXT_PUBLIC_ADMIN_KEY

// 운영 버전에서 log 안 찍히게 막는 코드 
if(process.env.NODE_ENV === 'production') {
  console.log = () => {}
  console.error = () => {}
  console.debug = () => {}

  window.onload = function () {
    document.addEventListener('contextmenu', function (e:any) {
      e.preventDefault();
    }, false);

    document.addEventListener('keydown', function (e:any) {
      if (e.keyCode == 123) { //F12키 막음
          disabledEvent(e);
      } 
    }, false);

    function disabledEvent(e:any) {
      if (e.stopPropagation) {
          e.stopPropagation();
      } else if (window.event) {
          window.event.cancelBubble = true;
      }
      e.preventDefault();
      return false;
    }
  }
}